# Generated by Django 4.1.1 on 2022-09-27 20:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('artist_id', models.DecimalField(decimal_places=0, max_digits=10)),
                ('artwork', models.ImageField(blank=True, null=True, upload_to='artworks/')),
                ('songs', models.DecimalField(decimal_places=0, default=0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('pfp', models.ImageField(blank=True, null=True, upload_to='artist_pfps/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('songs', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('albums', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('followers', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('about', models.TextField(blank=True, null=True)),
                ('artwork', models.ImageField(blank=True, null=True, upload_to='artworks/genres/')),
                ('songs', models.DecimalField(decimal_places=0, default=0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('album_id', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('artist_id', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('audio_file', models.FileField(upload_to='music/')),
                ('genre_id', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('track_number', models.DecimalField(decimal_places=0, default=0, max_digits=4)),
                ('year', models.DecimalField(decimal_places=0, default=0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=125)),
                ('bio', models.TextField(blank=True, null=True)),
                ('priv_key', models.TextField(blank=True, null=True)),
                ('pub_key', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('followers', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('following', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
