# Generated by Django 4.1.1 on 2022-09-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='year',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
    ]
