# Generated by Django 4.1.1 on 2022-09-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
