# Generated by Django 4.1.1 on 2022-10-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_album_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artwork',
            field=models.FileField(blank=True, null=True, upload_to='artworks/'),
        ),
    ]
