# Generated by Django 4.1.1 on 2022-09-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_song_audio_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('pfp', models.ImageField(blank=True, null=True, upload_to='artist_pfps/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('songs', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('albums', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('followers', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
            ],
        ),
    ]
