# Generated by Django 4.1.1 on 2022-09-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('artist_id', models.DecimalField(decimal_places=0, max_digits=10)),
                ('songs', models.DecimalField(decimal_places=0, default=0, max_digits=4)),
            ],
        ),
    ]
