# Generated by Django 4.1.1 on 2022-09-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artwork',
            field=models.ImageField(blank=True, null=True, upload_to='artworks/'),
        ),
    ]
