# Generated by Django 4.1.1 on 2022-09-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('artwork', models.ImageField(blank=True, null=True, upload_to='artworks/genres/')),
                ('songs', models.DecimalField(decimal_places=0, default=0, max_digits=4)),
            ],
        ),
    ]
