# Generated by Django 4.1.1 on 2022-09-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
