# Generated by Django 4.1.1 on 2022-09-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_genre_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='genre',
        ),
        migrations.AddField(
            model_name='song',
            name='genre_id',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
