# Generated by Django 4.1.1 on 2022-09-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_song_genre_song_genre_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='priv_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pub_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
